### ISSUE TITLE
Bug no cadastro de operações

### ISSUE THREAD

**Issue by pipfalcon** [felicityBR/calculadora#4]
Existe um bug no cadastro de operações que não permite cadastrar operações test test test

**Comment by pipfalcon** [comment]
teste teste teste teste teste Eu acho que até fica legar o Ezemplo com Z mas tem gente que perfere com X mesmo.

**Comment by pipfalcon** [comment]
Close

**Comment by cristina-front-end** [comment]
Existe um bug no cadastro de operações que não permite cadastrar operações.
